@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Committing changes...
git commit -m "Updated premium UI styling for Dashboard cards and Pagination dots"
echo Setting branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin https://github.com/ganitwali2025-maker/Cash-Bank-.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
